# Generated by Django 4.0.3 on 2022-03-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=100, verbose_name='station')),
                ('line', models.CharField(max_length=100, verbose_name='station')),
                ('admin_area', models.CharField(max_length=100, verbose_name='station')),
                ('district', models.CharField(max_length=100, verbose_name='station')),
                ('status', models.CharField(max_length=100, verbose_name='station')),
                ('entryID', models.IntegerField(verbose_name='station')),
            ],
        ),
    ]
