# Generated by Django 4.0.3 on 2022-03-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entryID',
            field=models.IntegerField(null=True, verbose_name='station'),
        ),
    ]
