# Generated by Django 4.0.3 on 2022-03-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initdb', '0002_alter_entry_entryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='admin_area',
            field=models.CharField(max_length=100, null=True, verbose_name='station'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='district',
            field=models.CharField(max_length=100, null=True, verbose_name='station'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='line',
            field=models.CharField(max_length=100, null=True, verbose_name='station'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='station',
            field=models.CharField(max_length=100, null=True, verbose_name='station'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(max_length=100, null=True, verbose_name='station'),
        ),
    ]
